### ISSUE TITLE
TypeError: Cannot set property 'privateData' of undefined

### ISSUE THREAD

**Issue by WestSide56** [safra36/RageMP-BigData#3]
TypeError: Cannot set property 'privateData' of undefined
    at Object.<anonymous> (D:\Games\RAGEMP\server-files\packages\project\modules\bigDataModule.js:25:30)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Games\RAGEMP\server-files\packages\project\index.js:686:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)

**Comment by WestSide56** [comment]
Seding Data Of Type: object
Seding Data Of Type: object
Seding Data Of Type: object
Data Tansmission fail request: ygYrJ8SjTJrSj6jREIrmGwtl5ZlVqCKF -2 - -2
Data Tansmission Failed! ygYrJ8SjTJrSj6jREIrmGwtl5ZlVqCKF - ygYrJ8SjTJrSj6jREIrmGwtl5ZlVqCKF - loadClothingInfo, loadClothingInfo
Data Tansmission fail request: ygYrJ8SjTJrSj6jREIrmGwtl5ZlVqCKF -2 - -2
Data Tansmission fail request: ygYrJ8SjTJrSj6jREIrmGwtl5ZlVqCKF -2 - -2
Data Tansmission fail request: YivO0ayhCepKi0QBpZehz76H7Wg5DXvW -2 - -2
Data Tansmission Failed! YivO0ayhCepKi0QBpZehz76H7Wg5DXvW - YivO0ayhCepKi0QBpZehz76H7Wg5DXvW - loadPropsInfo, loadPropsInfo
Data Tansmission fail request: YivO0ayhCepKi0QBpZehz76H7Wg5DXvW -2 - -2
Seding Data Of Type: object
Data Tansmission fail request: pNZ3W2cHfqNzchYudXDODuINxSHK3Al0 -2 - -2
Data Tansmission Failed! pNZ3W2cHfqNzchYudXDODuINxSHK3Al0 - pNZ3W2cHfqNzchYudXDODuINxSHK3Al0 - loadInventoryInfo, loadInventoryInfo
Data Tansmission fail request: pNZ3W2cHfqNzchYudXDODuINxSHK3Al0 -2 - -2
Seding Data Of Type: object
Data Tansmission end request: ZfRRvlsxWmbUqDHyWtdEn95BWpqh31Kp
Data Tansmission ended! ZfRRvlsxWmbUqDHyWtdEn95BWpqh31Kp - ZfRRvlsxWmbUqDHyWtdEn95BWpqh31Kp - loadClothingInfo, loadClothingInfo
Data Tansmission end request: ZfRRvlsxWmbUqDHyWtdEn95BWpqh31Kp
Seding Data Of Type: object
Data Tansmission end request: fxptFRQaW5n6vGUZVZnNY8sLEdN0jo3U
Data Tansmission ended! fxptFRQaW5n6vGUZVZnNY8sLEdN0jo3U - fxptFRQaW5n6vGUZVZnNY8sLEdN0jo3U - loadPropsInfo, loadPropsInfo
Data Tansmission end request: fxptFRQaW5n6vGUZVZnNY8sLEdN0jo3U
Data Tansmission end request: 3zrMLyvKwIVQUJmjzMi8xZHSyAZWvkKS
Data Tansmission ended! 3zrMLyvKwIVQUJmjzMi8xZHSyAZWvkKS - 3zrMLyvKwIVQUJmjzMi8xZHSyAZWvkKS - loadInventoryInfo, loadInventoryInfo

**Comment by safra36** [comment]
i'm aware if this issue, kind of fixed it already but it's still happening at some random places, this error wasn't happening before new rage-mp error reporting system

**Comment by matvejs16** [comment]
> i'm aware if this issue, kind of fixed it already but it's still happening at some random places, this error wasn't happening before new rage-mp error reporting system

Do you have solution to fix whis error?
![image](https://user-images.githubusercontent.com/74150728/152897063-abff94fc-b1dc-4bf2-9186-b65aaf0876ab.png)

**Comment by matvejs16** [comment]
Fix #4
